name: Deploy to Production
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+-[RT]C[0-9]+'

jobs: 
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: satak/webrequest-action@master
        with:
          url: http://ec2-54-190-53-106.us-west-2.compute.amazonaws.com:9000/api/v1/version/sync
          method: POST
          payload: '{"ref":"master","deploy":"true"}'
          headers: '{"Authorization": "Bearer ${{ secrets.BEARER_TOKEN }}"}'
